INSERT INTO department (name) VALUES ("Back Office");
INSERT INTO department (name) VALUES ("Software");
INSERT INTO department (name) VALUES ("Support");
INSERT INTO department (name) VALUES ("Kitchen");
INSERT INTO role (title, salary, dept_id) VALUES ("Owner", 21032, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Boss", 1171, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev, Sr", 25, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev, jr", 23, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Office Assciote", 13, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Cleaner", 11, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Butler", 35, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Cook", 14, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Footman", 7, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Sanitation", 1, 4);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mitch", "Gallup", 1,1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sally", "Mae", 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Fredrick", "Tate", 3, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Buster", "Douglas", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sal", "Kerry", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Alice", "Wonderland", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kate", "Leach", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Bob", "Jones", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Dorris", "Stevenson", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Elaine", "Merci", 7, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Frank", "Rivers", 8, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Gerry", "Billard", 8, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Harry", "Henry", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Inga", "Iguana", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Jerry", "Julian", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Keri", "Goodwin", 10, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Lenard", "Lemon", 10, 10);